set encoding=utf-8
set fenc=utf-8
set nobackup
set noswapfile
set autoread

set number
set smartindent
set showmatch
syntax enable

set list listchars=tab:\▸\-
set expandtab
set tabstop=2
set shiftwidth=2

set ignorecase
set incsearch
set wrapscan
set hlsearch
